### ISSUE TITLE
during installation, TypeError when calling method_exists

### ISSUE THREAD

**Issue by gregstoll** [gregstoll/gallery2#29]
From @hjschiller [here](https://github.com/gregstoll/gallery2/pull/28#issuecomment-1268025565): 

> Step 2 now results in:
>
> Warning: A non-numeric value encountered in /home/gallery2/install/steps/SystemChecksStep.class on line 43
>
> Warning: A non-numeric value encountered in /home/gallery2/install/steps/SystemChecksStep.class on line 43
>
> Warning: A non-numeric value encountered in /home/gallery2/install/steps/SystemChecksStep.class on line 43
>
> Fatal error: Uncaught TypeError: method_exists(): Argument https://github.com/gregstoll/gallery2/pull/1 ($object_or_class) must be of type object|string, null given in /home/gallery2/modules/core/classes/GalleryUtilities.class:1216 Stack trace: #0 /home/gallery2/modules/core/classes/GalleryUtilities.class(1216): method_exists() https://github.com/gregstoll/gallery2/pull/1 /home/gallery2/modules/core/classes/GalleryUtilities.class(1202): GalleryUtilities::readIndividualManifest() https://github.com/gregstoll/gallery2/issues/2 /home/gallery2/install/steps/SystemChecksStep.class(476): GalleryUtilities::readManifest() https://github.com/gregstoll/gallery2/pull/3 /home/gallery2/install/steps/SystemChecksStep.class(390): SystemChecksStep->CheckManifest() https://github.com/gregstoll/gallery2/issues/4 /home/gallery2/install/index.php(158): SystemChecksStep->processRequest() https://github.com/gregstoll/gallery2/issues/5 {main} thrown in /home/gallery2/modules/core/classes/GalleryUtilities.class on line 1216

**Comment by gregstoll** [comment]
@hjschiller - can you verify that this is fixed?

**Comment by hjschiller** [comment]
@gregstoll  two warnings on step two... then fails on step 8.

I did see two warnings on step two, but can safely ignore and continue...  
(doesn't bother me if it doesn't bother you)

warning 1 seems to be regadding php.ini missing output_buffering, but AFAIK it is properly configured,
and apache restarted.

Warning 2 is regarding 274 files that have been modified... 
I'm guess these are changes that have been made over the years, but there is some signature that it checks,
and now the files don't match the signature.  

Step 8 errors with:
Fatal error: Uncaught Error: Non-static method CoreModuleExtras::upgrade() cannot be called statically in /home/gallery2/modules/core/module.inc:486 Stack trace: #0 /home/gallery2/modules/core/classes/GalleryModule.class(175): CoreModule->upgrade() #1 /home/gallery2/install/steps/InstallCoreModuleStep.class(143): GalleryModule->installOrUpgrade() #2 /home/gallery2/install/index.php(158): InstallCoreModuleStep->processRequest() #3 {main} thrown in /home/gallery2/modules/core/module.inc on line 486

See output below:

warning 1:
-----------------------------------
gallery2/install/index.php?step=2
========================
Warning: Output buffering is enabled in your PHP by the output_buffering parameter(s) in php.ini. Gallery can function with this setting - downloading files is even faster - but Gallery might be unable to serve large files (e.g. large videos) and run into the memory limit. Also, some features like the progress bars might not work correctly if output buffering is enabled unless ini_set() is allowed.
-----------------------------------

this is strange because I verified the following an restarted apache2:
$ grep output_buffering /etc/php/8.1/apache2/php.ini
; output_buffering
output_buffering = 4096
;   performance, enable output_buffering in addition.

$ grep output_buffering /etc/php/7.4/apache2/php.ini
; output_buffering
output_buffering = 4096
;   performance, enable output_buffering in addition.


warning 2:
-----------------------------------
gallery2/install/index.php?step=2
=========================
Modified files (274)

init.inc
install/InstallStep.class
install/index.php
install/steps/AuthenticateStep.class
install/steps/CreateConfigFileStep.class
lib/adodb/adodb-iterator.inc.php
lib/adodb/adodb-perf.inc.php
lib/adodb/adodb-time.inc.php
lib/adodb/adodb.inc.php
lib/adodb/drivers/adodb-ado.inc.php
lib/adodb/drivers/adodb-ado5.inc.php
lib/adodb/drivers/adodb-ado_mssql.inc.php
lib/adodb/drivers/adodb-db2.inc.php
lib/adodb/drivers/adodb-mysql.inc.php
lib/adodb/drivers/adodb-mysqli.inc.php
lib/adodb/drivers/adodb-mysqlt.inc.php
lib/adodb/drivers/adodb-oci8.inc.php
lib/adodb/drivers/adodb-oci8po.inc.php
lib/adodb/drivers/adodb-oracle.inc.php
lib/adodb/drivers/adodb-postgres64.inc.php
lib/adodb/drivers/adodb-postgres7.inc.php
lib/bbcode/stringparser.class.php
lib/pear/HTMLSax3.php
lib/pear/Safe.php
lib/pear/mime.php
lib/pear/mimePart.php
lib/phpass/PasswordHash.inc
lib/smarty/Smarty.class.php
lib/smarty/Smarty_Compiler.class.php
lib/smarty_plugins/modifier.markup.php
lib/support/GallerySetupUtilities.class
lib/support/SupportStatusTemplate.class
lib/support/chmod.php
lib/support/phpinfo.php
upgrade/UpgradeStep.class
upgrade/index.php
upgrade/steps/UpgradeOtherModulesStep.class
modules/jpegtran/classes/JpegtranToolkitHelper.class
modules/jpegtran/module.inc
modules/comment/CommentSiteAdmin.inc
modules/comment/classes/GalleryComment.class
modules/comment/classes/GalleryCommentHelper.class
modules/comment/module.inc
modules/sizelimit/module.inc
modules/mp3audio/module.inc
modules/multiroot/module.inc
modules/albumselect/Callbacks.inc
modules/albumselect/module.inc
modules/hidden/classes/HiddenHelper.class
modules/hidden/module.inc
modules/randomhighlight/module.inc
modules/reupload/module.inc
modules/permalinks/classes/PermalinksMapHelper.class
modules/permalinks/module.inc
modules/fotokasten/lib/nusoap.inc
modules/fotokasten/module.inc
modules/exif/ExifDescriptionOption.inc
modules/exif/SwitchDetailMode.inc
modules/exif/classes/ExifExtractor.class
modules/exif/classes/ExifHelper.class
modules/exif/lib/JPEG/JPEG.inc
modules/exif/lib/exifer/exif.inc
modules/exif/lib/exifer/makers/nikon.inc
modules/exif/module.inc
modules/slideshow/classes/PicLensHelper.class
modules/slideshow/classes/SlideshowHelper.class
modules/slideshow/module.inc
modules/imageblock/classes/ImageBlockHelper.class
modules/imageblock/module.inc
modules/publishxp/module.inc
modules/dynamicalbum/PopularAlbum.inc
modules/dynamicalbum/RandomAlbum.inc
modules/dynamicalbum/UpdatesAlbum.inc
modules/dynamicalbum/module.inc
modules/replica/module.inc
modules/rewrite/RewriteModuleExtras.inc
modules/rewrite/classes/RewriteApi.class
modules/rewrite/classes/RewriteSimpleHelper.class
modules/rewrite/classes/parsers/isapirewrite/parser.inc
modules/rewrite/classes/parsers/modrewrite/parser.inc
modules/rewrite/classes/parsers/pathinfo/parser.inc
modules/rewrite/module.inc
modules/rearrange/module.inc
modules/ecard/classes/EcardHelper.class
modules/ecard/module.inc
modules/slideshowapplet/module.inc
modules/useralbum/module.inc
modules/archiveupload/module.inc
modules/getid3/lib/getid3/getid3.inc
modules/getid3/lib/getid3/getid3.lib.inc
modules/getid3/lib/getid3/module.archive.zip.inc
modules/getid3/lib/getid3/module.audio-video.quicktime.inc
modules/getid3/lib/getid3/module.audio.mp3.inc
modules/getid3/lib/getid3/module.audio.ogg.inc
modules/getid3/lib/getid3/module.misc.iso.inc
modules/getid3/lib/getid3/module.tag.apetag.inc
modules/getid3/lib/getid3/module.tag.id3v1.inc
modules/getid3/lib/getid3/module.tag.id3v2.inc
modules/getid3/lib/getid3/module.tag.lyrics3.inc
modules/getid3/module.inc
modules/migrate/module.inc
modules/picasa/ItemAddFromPicasa.inc
modules/picasa/module.inc
modules/newitems/module.inc
modules/customfield/classes/CustomFieldHelper.class
modules/customfield/module.inc
modules/netpbm/module.inc
modules/shutterfly/module.inc
modules/core/CombinedJavascript.inc
modules/core/CoreModuleExtras.inc
modules/core/ErrorPage.inc
modules/core/ItemAdd.inc
modules/core/ItemAddFromBrowser.inc
modules/core/ItemAdmin.inc
modules/core/ItemEdit.inc
modules/core/PluginCallback.inc
modules/core/ShowItem.inc
modules/core/classes/FlockLockSystem.class
modules/core/classes/Gallery.class
modules/core/classes/GalleryAlbumItem.class
modules/core/classes/GalleryChildEntity.class
modules/core/classes/GalleryController.class
modules/core/classes/GalleryCoreApi.class
modules/core/classes/GalleryDataCache.class
modules/core/classes/GalleryDataItem.class
modules/core/classes/GalleryDerivative.class
modules/core/classes/GalleryDerivativeImage.class
modules/core/classes/GalleryDynamicAlbum.class
modules/core/classes/GalleryEmbed.class
modules/core/classes/GalleryEntity.class
modules/core/classes/GalleryEvent.class
modules/core/classes/GalleryFileSystemEntity.class
modules/core/classes/GalleryGroup.class
modules/core/classes/GalleryItem.class
modules/core/classes/GalleryLockSystem.class
modules/core/classes/GalleryModule.class
modules/core/classes/GalleryMovieItem.class
modules/core/classes/GalleryPersistent.class
modules/core/classes/GalleryPhotoItem.class
modules/core/classes/GalleryPhpVm.class
modules/core/classes/GalleryPlugin.class
modules/core/classes/GalleryRepository.class
modules/core/classes/GalleryRepositoryIndex.class
modules/core/classes/GallerySession.class
modules/core/classes/GallerySortInterface_1_2.class
modules/core/classes/GalleryStatus.class
modules/core/classes/GalleryStorage.class
modules/core/classes/GalleryStorage/Db2Storage.class
modules/core/classes/GalleryStorage/GalleryDatabaseImport.class
modules/core/classes/GalleryStorage/OracleStorage.class
modules/core/classes/GalleryStorage/PostgreSqlStorage.class
modules/core/classes/GalleryStorage/SQLiteStorage.class
modules/core/classes/GalleryTemplate.class
modules/core/classes/GalleryTemplateAdapter.class
modules/core/classes/GalleryTheme.class
modules/core/classes/GalleryToolkit.class
modules/core/classes/GalleryTranslator.class
modules/core/classes/GalleryUnknownItem.class
modules/core/classes/GalleryUrlGenerator.class
modules/core/classes/GalleryUser.class
modules/core/classes/GalleryUtilities.class
modules/core/classes/GalleryView.class
modules/core/classes/helpers/GalleryCharsetHelper_medium.class
modules/core/classes/helpers/GalleryCharsetHelper_simple.class
modules/core/classes/helpers/GalleryChildEntityHelper_simple.class
modules/core/classes/helpers/GalleryDerivativeHelper_advanced.class
modules/core/classes/helpers/GalleryDerivativeHelper_medium.class
modules/core/classes/helpers/GalleryDerivativeHelper_simple.class
modules/core/classes/helpers/GalleryEntityHelper_medium.class
modules/core/classes/helpers/GalleryEntityHelper_simple.class
modules/core/classes/helpers/GalleryEventHelper_simple.class
modules/core/classes/helpers/GalleryEventLogHelper_medium.class
modules/core/classes/helpers/GalleryFactoryHelper_medium.class
modules/core/classes/helpers/GalleryFactoryHelper_simple.class
modules/core/classes/helpers/GalleryFileSystemEntityHelper_medium.class
modules/core/classes/helpers/GalleryFileSystemEntityHelper_simple.class
modules/core/classes/helpers/GalleryGroupHelper_simple.class
modules/core/classes/helpers/GalleryItemAttributesHelper_advanced.class
modules/core/classes/helpers/GalleryItemAttributesHelper_medium.class
modules/core/classes/helpers/GalleryItemAttributesHelper_simple.class
modules/core/classes/helpers/GalleryItemHelper_advanced.class
modules/core/classes/helpers/GalleryItemHelper_medium.class
modules/core/classes/helpers/GalleryItemHelper_simple.class
modules/core/classes/helpers/GalleryLockHelper_simple.class
modules/core/classes/helpers/GalleryMimeTypeHelper_advanced.class
modules/core/classes/helpers/GalleryMimeTypeHelper_simple.class
modules/core/classes/helpers/GalleryPermissionHelper_advanced.class
modules/core/classes/helpers/GalleryPermissionHelper_simple.class
modules/core/classes/helpers/GalleryPluginHelper_medium.class
modules/core/classes/helpers/GalleryPluginHelper_simple.class
modules/core/classes/helpers/GalleryThemeHelper_medium.class
modules/core/classes/helpers/GalleryToolkitHelper_medium.class
modules/core/classes/helpers/GalleryToolkitHelper_simple.class
modules/core/classes/helpers/GalleryTranslatorHelper_medium.class
modules/core/classes/helpers/GalleryUserGroupHelper_medium.class
modules/core/classes/helpers/GalleryUserGroupHelper_simple.class
modules/core/classes/helpers/GalleryUserHelper_medium.class
modules/core/classes/helpers/GalleryUserHelper_simple.class
modules/core/classes/helpers/MailHelper_simple.class
modules/core/classes/helpers/MaintenanceHelper_simple.class
modules/core/classes/helpers/UserRecoverPasswordHelper_simple.class
modules/core/classes/helpers/WebHelper_simple.class
modules/core/module.inc
modules/panorama/classes/PanoramaHelper.class
modules/panorama/module.inc
modules/nokiaupload/module.inc
modules/search/classes/SearchUtilities.class
modules/search/module.inc
modules/multilang/module.inc
modules/rating/RatingAlbum.inc
modules/rating/classes/RatingHelper.class
modules/rating/module.inc
modules/flashvideo/module.inc
modules/captcha/CaptchaImage.inc
modules/captcha/CaptchaSiteAdmin.inc
modules/captcha/module.inc
modules/imageframe/module.inc
modules/sitemap/module.inc
modules/cart/classes/CartHelper.class
modules/cart/module.inc
modules/colorpack/module.inc
modules/mime/module.inc
modules/thumbnail/classes/ThumbnailHelper.class
modules/thumbnail/classes/ThumbnailImage.class
modules/thumbnail/module.inc
modules/ffmpeg/module.inc
modules/linkitem/ItemAddLinkItem.inc
modules/linkitem/classes/GalleryLinkItem.class
modules/linkitem/classes/LinkItemToolkit.class
modules/linkitem/module.inc
modules/password/PasswordOption.inc
modules/password/classes/PasswordHelper.class
modules/password/module.inc
modules/quotas/classes/GalleryQuotasHelper.class
modules/quotas/module.inc
modules/httpauth/classes/HttpAuthHelper.class
modules/httpauth/module.inc
modules/watermark/module.inc
modules/remote/classes/GalleryRemoteProperties.class
modules/remote/module.inc
modules/webdav/ItemAddWebDav.inc
modules/webdav/lib/HTTP/WebDAV/Server.php
modules/webdav/module.inc
modules/zipcart/module.inc
modules/keyalbum/Callbacks.inc
modules/keyalbum/KeywordAlbum.inc
modules/keyalbum/module.inc
modules/members/module.inc
modules/imagemagick/module.inc
modules/photoaccess/classes/PhotoAccessHelper.class
modules/photoaccess/module.inc
modules/rss/module.inc
modules/register/module.inc
modules/itemadd/module.inc
modules/icons/module.inc
modules/digibug/module.inc
modules/webcam/ItemAddWebCam.inc
modules/webcam/module.inc
modules/notification/classes/NotificationHelper.class
modules/notification/module.inc
modules/thumbpage/module.inc
modules/gd/classes/GdToolkit.class
modules/gd/classes/GdToolkitHelper.class
modules/gd/module.inc
modules/squarethumb/classes/SquareThumbToolkit.class
modules/squarethumb/module.inc
modules/uploadapplet/module.inc
modules/snapgalaxy/classes/SnapGalaxyHelper.class
modules/snapgalaxy/module.inc
themes/ajaxian/theme.inc
themes/classic/theme.inc
themes/floatrix/theme.inc
themes/tile/theme.inc
themes/carbon/theme.inc

**Comment by gregstoll** [comment]
OK, well, that's progress :-)

I filed #31 for the warning (which I'll ignore for now) and #32 for the error.
